version: "3.8"

services:
  nginx:
    container_name: nginx_transcendence
    image: nginx_ssl
    build: ./srcs/nginx
    networks:
      - transproxy
    volumes:
      - ./srcs/nginx/volumes:/datas
    ports:
      - "8081:80"
      - "8082:443"
    restart: always

  react:
    container_name: react_transcendence
    image: react
    build: ./srcs/front_react
    networks:
      - transproxy
    restart: always

  nestjs:
    container_name: nestjs_transcendence
    image: nestjs
    build: ./srcs/back_nestjs
    networks:
      - transcendence
      - transproxy
    volumes:
      - ./srcs/back_nestjs:/nestjs
      - pictures:/nestjs/datas/users/avatars
    env_file:
      - .env
    restart: always

  postgres:
    container_name: postgres_transcendence
    image: postgres:14.2-alpine
    networks:
      - transcendence
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /volume1/docker/transcendence/db
  pictures:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /volume1/docker/transcendence/pictures

networks:
  transcendence:
  transproxy:
