version: '3.8'

services:
  react:
    container_name: react_transcendence
    image: react
    build: ./srcs/front_react
    depends_on:
      - nestjs
    ports:
      - "3000:3000"
    networks:
      - transcendence
    volumes:
      - ./srcs/front_react:/react
    restart: always

  nestjs:
    container_name: nestjs_transcendence
    image: nestjs
    build: ./srcs/back_nestjs
    depends_on:
      - postgres
    ports:
      - "4000:3000"
    env_file:
      - .env
    networks:
      - transcendence
    volumes:
      - ./srcs/back_nestjs:/nestjs
    restart: always

  postgres:
    container_name: postgres_transcendence
    image: postgres:14.2-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - transcendence

  pgadmin:
    container_name: pgadmin_transcendence
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    env_file:
      - .env
      - .pgadmin.env
    volumes:
      - ./.servers.json:/pgadmin4/servers.json
    networks:
      - transcendence

networks:
  transcendence:
