version: "3.8"

services:
  nginx:
    container_name: nginx_transcendence
    image: nginx:latest
    networks:
      - transproxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    restart: always

  react:
    container_name: react_transcendence
    image: react
    build: ./srcs/front_react
    depends_on:
      - nestjs
    networks:
      - transproxy
    volumes:
      - ./srcs/front_react:/react
    restart: always

  nestjs:
    container_name: nestjs_transcendence
    image: nestjs
    build: ./srcs/back_nestjs
    depends_on:
      - postgres
    networks:
      - transcendence
    volumes:
      - ./srcs/back_nestjs:/nestjs
    restart: always

  postgres:
    container_name: postgres_transcendence
    image: postgres:14.2-alpine
    networks:
      - transcendence

networks:
  transcendence:
  transproxy:
