#!/bin/bash

for i in {1..100}
do
	curl --location --request POST 'http://localhost:4000/channel/falseUsergenerator' \
	--header 'Content-Type: application/json' \
	--data-raw '{
		    "username": "player'$i'",
			    "channel": {
					        "name":"e9b73768-f5d5-4d3b-9d55-7c1479cf5cee"
							    }
	}'
done

