#!/bin/bash

for i in {1..50}
do
	curl --location --request POST 'http://localhost:4000/channel/falseUsergenerator' \
--header 'Content-Type: application/json' \
--data-raw '{
    "username": "player'$i'",
    "channel": {
    	"id":"74075785-f9e1-477e-b0c4-2932b968b139",
        "password":"pwd"
    }
}'
done

